//! Render an [`InferenceOutput`] as a `.dataseed` source file.
//!
//! We don't go through `ast::File` because that loses the per-field
//! comments. Instead we format the text directly, then run the resulting
//! string through the dataseed parser and semantic checker as a self-test:
//! if our output won't parse or won't pass semantic analysis, that's a
//! Phase 4 bug, not a user error.

use std::fmt::Write as _;

use crate::ast::{Call, OutputKind, Value};
use crate::harvest::infer::{InferenceOutput, InferredColumn, InferredTable};
use crate::harvest::model::HarvestSchema;
use crate::harvest::topo;

pub fn render(
    schema: &HarvestSchema,
    inference: &InferenceOutput,
    output_mode: OutputKind,
    scale: f64,
) -> Result<String, String> {
    let mut out = String::new();
    write_header(&mut out, schema)?;

    let topo_result = topo::sort(schema);
    if topo_result.has_cycle {
        writeln!(
            out,
            "# WARNING: source schema has a FK cycle; you'll need to break it manually"
        )
        .ok();
    }
    writeln!(out).ok();

    writeln!(out, "output: {}", output_mode_str(output_mode)).ok();
    writeln!(out).ok();

    for table_name in &topo_result.order {
        let Some(inferred) = inference.tables.get(table_name) else {
            continue;
        };
        write_table_block(&mut out, inferred);
        writeln!(out).ok();
    }

    for table_name in &topo_result.order {
        let Some(source_table) = schema.tables.iter().find(|t| &t.name == table_name) else {
            continue;
        };
        let scaled = scale_count(source_table.estimated_rows, scale);
        write!(out, "generate {table_name}: {scaled}").ok();
        if source_table.estimated_rows >= 10_000_000 && (scale - 1.0).abs() < 1e-9 {
            write!(
                out,
                "  # source had {} rows; consider --scale 0.001 for fixture-sized data",
                source_table.estimated_rows
            )
            .ok();
        }
        writeln!(out).ok();
    }

    Ok(out)
}

fn write_header(out: &mut String, schema: &HarvestSchema) -> Result<(), String> {
    writeln!(out, "# Generated by {}", schema.source.invocation)
        .map_err(|e| e.to_string())?;
    writeln!(
        out,
        "# Source: {} database, {} schema, harvested {}",
        schema.source.database,
        schema.source.schema,
        schema.source.harvested_at.format("%Y-%m-%dT%H:%M:%SZ")
    )
    .map_err(|e| e.to_string())?;
    let summary: Vec<String> = schema
        .tables
        .iter()
        .map(|t| format!("{} {}", t.estimated_rows, t.name))
        .collect();
    if !summary.is_empty() {
        writeln!(out, "# {}", summary.join(", ")).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn write_table_block(out: &mut String, table: &InferredTable) {
    writeln!(out, "table {} {{", table.name).ok();
    for c in &table.columns {
        write_field_line(out, c);
    }
    writeln!(out, "}}").ok();
}

fn write_field_line(out: &mut String, col: &InferredColumn) {
    let call_str = format_call(&col.call);
    match &col.inline_comment {
        Some(comment) if !comment.is_empty() => {
            writeln!(out, "  {}: {}  # {}", col.name, call_str, comment).ok();
        }
        _ => {
            writeln!(out, "  {}: {}", col.name, call_str).ok();
        }
    }
}

fn format_call(call: &Call) -> String {
    if call.function == "sequence" && call.positional.is_empty() && call.kwargs.is_empty() {
        return "sequence".to_string();
    }
    let mut parts = Vec::new();
    for v in &call.positional {
        parts.push(format_value(v));
    }
    for (k, v) in &call.kwargs {
        parts.push(format!("{k}: {}", format_value(v)));
    }
    format!("{}({})", call.function, parts.join(", "))
}

fn format_value(v: &Value) -> String {
    match v {
        Value::Number(n) => format_number(*n),
        Value::String(s) => format!("\"{}\"", escape_string(s)),
        Value::Bool(b) => b.to_string(),
        Value::Array(items) => {
            let inner: Vec<String> = items.iter().map(format_value).collect();
            format!("[{}]", inner.join(", "))
        }
        Value::ColumnRef { table, column } => format!("{table}.{column}"),
        Value::Range { lo, hi } => format!("{lo}..{hi}"),
    }
}

fn format_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        // Avoid emitting "5.0" for what was clearly an integer (sequence
        // start, segment count, etc.).
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

fn output_mode_str(k: OutputKind) -> &'static str {
    match k {
        OutputKind::Sql => "sql",
        OutputKind::Json => "json",
        OutputKind::Postgis => "postgis",
    }
}

fn scale_count(n: u64, scale: f64) -> u64 {
    if n == 0 {
        return 0;
    }
    let raw = (n as f64) * scale;
    if raw < 1.0 {
        1
    } else {
        raw.round() as u64
    }
}

/// Round-trip the rendered text through the dataseed parser and semantic
/// checker. A failure here means inference produced something this tool
/// itself wouldn't accept — a bug, not a user problem.
pub fn self_check(text: &str) -> Result<(), String> {
    let file = crate::parser::parse(text).map_err(|e| format!("parser rejected: {e}"))?;
    let report = crate::semantic::check(&file);
    if !report.is_ok() {
        let msgs: Vec<String> = report.errors.iter().map(|e| e.to_string()).collect();
        return Err(format!("semantic rejected: {}", msgs.join("; ")));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Call, Value};

    #[test]
    fn format_call_omits_parens_for_bare_sequence() {
        let c = Call {
            function: "sequence".to_string(),
            positional: vec![],
            kwargs: vec![],
            line: 0,
            col: 0,
        };
        assert_eq!(format_call(&c), "sequence");
    }

    #[test]
    fn format_call_emits_columnref_as_dotted() {
        let c = Call {
            function: "ref".to_string(),
            positional: vec![Value::ColumnRef {
                table: "users".to_string(),
                column: "id".to_string(),
            }],
            kwargs: vec![],
            line: 0,
            col: 0,
        };
        assert_eq!(format_call(&c), "ref(users.id)");
    }

    #[test]
    fn format_call_emits_kwargs_after_positional() {
        let c = Call {
            function: "randomRealNumber".to_string(),
            positional: vec![Value::Number(1.0), Value::Number(45.0)],
            kwargs: vec![("decimals".to_string(), Value::Number(2.0))],
            line: 0,
            col: 0,
        };
        assert_eq!(
            format_call(&c),
            "randomRealNumber(1, 45, decimals: 2)"
        );
    }

    #[test]
    fn format_value_array_of_numbers() {
        let v = Value::Array(vec![
            Value::Number(3.3140),
            Value::Number(50.7510),
            Value::Number(7.2275),
            Value::Number(53.555),
        ]);
        assert_eq!(format_value(&v), "[3.314, 50.751, 7.2275, 53.555]");
    }

    #[test]
    fn scale_count_rounds_and_floors_to_1() {
        assert_eq!(scale_count(1247, 1.0), 1247);
        assert_eq!(scale_count(1247, 0.1), 125);
        assert_eq!(scale_count(0, 1.0), 0);
        // Anything > 0 scales to at least 1 row.
        assert_eq!(scale_count(5, 0.01), 1);
    }
}
